# .github/actions/cached-deps/action.yml
name: 'Get & Cache Dependencies'
description: 'Get & Cache Dependencies(via yarn) for faster builds'
runs:
  using: 'composite'
  steps:
    - name: 'Cache Dependencies'
      uses: 'actions/cache@v3'
      id: cache-node-modules
      with:
        path: 'node_modules'
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      # only run yarn i if cache not found
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn
      # the shell to be used is required in composite custom actions
      shell: bash
